warn = [
  "clippy::perf",
  "clippy::nursery",
  "clippy::needless_collect",
  "clippy::map_flatten",
  "clippy::or_fun_call",
  "clippy::inefficient_to_string",
  "clippy::unnecessary_wraps",
  "clippy::useless_conversion",
]
allow = [
  "clippy::module_name_repetitions",
]
