use liq_ta::indicators::candlestick::*;

fn make_ohlc(n: usize) -> (Vec<f64>, Vec<f64>, Vec<f64>, Vec<f64>) {
    let mut open = Vec::with_capacity(n);
    let mut high = Vec::with_capacity(n);
    let mut low = Vec::with_capacity(n);
    let mut close = Vec::with_capacity(n);

    let mut p = 100.0_f64;
    for i in 0..n {
        p += 0.3 + (i as f64 * 0.13).sin() * 0.2;
        let o = p - 0.2;
        let c = p + 0.25;
        open.push(o);
        high.push(o.max(c) + 0.7);
        low.push(o.min(c) - 0.65);
        close.push(c);
    }

    (open, high, low, close)
}

macro_rules! expect_validation_err {
    ($name:literal, $f:ident, $into_f:ident, $o:expr, $h:expr, $l:expr, $c:expr) => {{
        let short_close = &$c[..$c.len() - 1];
        assert!(
            $f($o, $h, $l, short_close).is_err(),
            "{} alloc should reject mismatched input lengths",
            $name
        );

        let mut short_out = vec![0_i32; $o.len() - 1];
        assert!(
            $into_f($o, $h, $l, $c, &mut short_out).is_err(),
            "{} into should reject short output buffer",
            $name
        );

        let mut ok_out = vec![0_i32; $o.len()];
        assert!(
            $into_f($o, $h, $l, short_close, &mut ok_out).is_err(),
            "{} into should reject mismatched input lengths",
            $name
        );
    }};
}

#[test]
fn candlestick_patterns_reject_mismatched_inputs_and_output_sizes() {
    let (open, high, low, close) = make_ohlc(64);

    expect_validation_err!(
        "single/doji",
        cdl_doji,
        cdl_doji_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/dragonfly_doji",
        cdl_dragonfly_doji,
        cdl_dragonfly_doji_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/gravestone_doji",
        cdl_gravestone_doji,
        cdl_gravestone_doji_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/longleg_doji",
        cdl_longleg_doji,
        cdl_longleg_doji_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/rickshaw_man",
        cdl_rickshaw_man,
        cdl_rickshaw_man_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/marubozu",
        cdl_marubozu,
        cdl_marubozu_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/closing_marubozu",
        cdl_closing_marubozu,
        cdl_closing_marubozu_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/spinning_top",
        cdl_spinning_top,
        cdl_spinning_top_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/high_wave",
        cdl_high_wave,
        cdl_high_wave_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/long_line",
        cdl_long_line,
        cdl_long_line_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/short_line",
        cdl_short_line,
        cdl_short_line_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/hammer",
        cdl_hammer,
        cdl_hammer_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/hanging_man",
        cdl_hanging_man,
        cdl_hanging_man_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/inverted_hammer",
        cdl_inverted_hammer,
        cdl_inverted_hammer_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/shooting_star",
        cdl_shooting_star,
        cdl_shooting_star_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/takuri",
        cdl_takuri,
        cdl_takuri_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "single/belt_hold",
        cdl_belt_hold,
        cdl_belt_hold_into,
        &open,
        &high,
        &low,
        &close
    );

    expect_validation_err!(
        "two/engulfing",
        cdl_engulfing,
        cdl_engulfing_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/harami",
        cdl_harami,
        cdl_harami_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/harami_cross",
        cdl_harami_cross,
        cdl_harami_cross_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/piercing",
        cdl_piercing,
        cdl_piercing_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/dark_cloud_cover",
        cdl_dark_cloud_cover,
        cdl_dark_cloud_cover_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/doji_star",
        cdl_doji_star,
        cdl_doji_star_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/kicking",
        cdl_kicking,
        cdl_kicking_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/kicking_by_length",
        cdl_kicking_by_length,
        cdl_kicking_by_length_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/matching_low",
        cdl_matching_low,
        cdl_matching_low_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/homing_pigeon",
        cdl_homing_pigeon,
        cdl_homing_pigeon_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/in_neck",
        cdl_in_neck,
        cdl_in_neck_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/on_neck",
        cdl_on_neck,
        cdl_on_neck_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/thrusting",
        cdl_thrusting,
        cdl_thrusting_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/separating_lines",
        cdl_separating_lines,
        cdl_separating_lines_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/counter_attack",
        cdl_counter_attack,
        cdl_counter_attack_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/2crows",
        cdl_2crows,
        cdl_2crows_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/hikkake",
        cdl_hikkake,
        cdl_hikkake_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "two/hikkake_mod",
        cdl_hikkake_mod,
        cdl_hikkake_mod_into,
        &open,
        &high,
        &low,
        &close
    );

    expect_validation_err!(
        "three/morning_star",
        cdl_morning_star,
        cdl_morning_star_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "three/evening_star",
        cdl_evening_star,
        cdl_evening_star_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "three/morning_doji_star",
        cdl_morning_doji_star,
        cdl_morning_doji_star_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "three/evening_doji_star",
        cdl_evening_doji_star,
        cdl_evening_doji_star_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "three/abandoned_baby",
        cdl_abandoned_baby,
        cdl_abandoned_baby_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "three/3white_soldiers",
        cdl_3white_soldiers,
        cdl_3white_soldiers_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "three/3black_crows",
        cdl_3black_crows,
        cdl_3black_crows_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "three/3inside",
        cdl_3inside,
        cdl_3inside_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "three/3outside",
        cdl_3outside,
        cdl_3outside_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "three/3line_strike",
        cdl_3line_strike,
        cdl_3line_strike_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "three/3stars_in_south",
        cdl_3stars_in_south,
        cdl_3stars_in_south_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "three/tristar",
        cdl_tristar,
        cdl_tristar_into,
        &open,
        &high,
        &low,
        &close
    );
    expect_validation_err!(
        "three/identical_3crows",
        cdl_identical_3crows,
        cdl_identical_3crows_into,
        &open,
        &high,
        &low,
        &close
    );
}
